<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>LogIn</title>
</head>
<body>
<h1>Login</h1>
<form method="post">
    Mail: <input type="text" name="mail"/>
    <br>
    Password: <input type="password" name="password"/>
    <br>
    <input type="submit" value="submit"/>
</form>
<span>Sin cuenta? <a href="../Controllers/signUpController.php">Crea una cuenta</a></span>
</body>
</html>


